version: "2"
services:
  webapi:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - monitoring
    ports: 
      - 5000:5000
      - 5001:5001
      - 1234:1234
    command: /bin/sh -c "while sleep 1000; do :; done"  
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always 
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
  telegraf:
    image: telegraf 
    container_name: telegraf 
    restart: always 
    networks:
      - monitoring
    volumes:
      - ./../telegraf-volume/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=user
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true